/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

//€1 = Y177.31
public class App {
    
    public Double yenConverter() {
        double exchangeRate1 = 177.31;
        double euro = 13;
        double yen = euro*exchangeRate1;
        return yen;
    }

    public Double euroConverter(){
        double exchangeRate2 = 0.0056;
        double yen = 3000;
        double euro = yen*exchangeRate2;
        return euro;
    }

    public static void main(String[] args) {
        System.out.println(new App().yenConverter());
        System.out.println(new App().euroConverter());
    }
}
